#Proyecto Machine Learning

## Grupo Zeta:

- Wagner Dueñas
- Cindy Cunalata
- Viviana Huachizaca

# Entregable 1

## 0. Revisión preliminar de los datos:
Identifique el número de características, sus tipos de datos:

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from constants import initial_dir

In [9]:
df_test = pd.read_csv(f'{initial_dir}/vehiculos_test.csv')
df_test.head()

,index,marca,modelo,color,anio_registro,tipo_vehiculo,millas_recorridas,tamanio_motor,transmision,tipo_combustible,precio_vehiculo,num_asientos,num_puertas,problema_averia,id_problema_averia,fecha_averia,complejidad_reparacion,costo_reparacion,horas_reparacion,fecha_reparacion
0,0,Volkswagen,Passat,Blue,2015.0,Saloon,37723.0,2.0L,Automatic,Diesel,12690.0,5.0,4.0,Flat Tyres,0,2018-04-03,1,23.807,1.0,2018-04-03
1,1,Jaguar,XF,White,2014.0,Saloon,78000.0,2.2L,Automatic,Diesel,13490.0,5.0,4.0,Steering Wheel Shaking,0,2018-05-14,3,73.490,3.0,2018-05-14
2,2,Volkswagen,Polo,Orange,2010.0,Hatchback,44936.0,1.4L,Automatic,Petrol,NaN,5.0,5.0,Alternator Failing,0,2018-08-16,1,160.000,2.0,2018-08-16
3,3,Audi,S5,Black,2014.0,Coupe,29000.0,3.0L,Automatic,Petrol,22990.0,4.0,3.0,Steering Wheel Shaking,0,2018-07-24,1,42.990,1.0,2018-07-24
4,4,Toyota,Yaris,Black,2016.0,Hatchback,18037.0,1.33L,Manual,Petrol,9293.0,5.0,5.0,Electrical Issue,2,2018-05-04,1,28.586,0.5,2018-05-04

In [10]:
df_train = pd.read_csv('vehiculos_train.csv')
df_train.head()

,marca,modelo,color,anio_registro,tipo_vehiculo,millas_recorridas,tamanio_motor,transmision,tipo_combustible,precio_vehiculo,num_asientos,num_puertas,problema_averia,id_problema_averia,fecha_averia,complejidad_reparacion,costo_reparacion,horas_reparacion,fecha_reparacion,fraude
0,Jeep,Renegade,Black,2018.0,SUV,17.0,1.4L,Manual,Petrol,16000.0,5.0,5.0,Electrical Issue,5,2018-06-07,1,76.0000,3.0,2018-06-07,0
1,Vauxhall,Insignia,Grey,2011.0,Hatchback,93000.0,NaN,Manual,Petrol,3995.0,5.0,5.0,Excessive Emissions,0,2018-08-09,1,23.5955,1.0,2018-08-09,0
2,Mercedes-Benz,GLC Class,White,2019.0,SUV,6879.0,2.0L,Automatic,Diesel,31498.0,5.0,5.0,Windscreen Crack,0,2021-06-17,1,38.8988,1.0,2021-06-17,0
3,Renault,NaN,NaN,2014.0,Hatchback,20669.0,1.2L,Manual,Petrol,6950.0,5.0,5.0,Brake Pads Worn,0,2018-04-23,1,43.4750,2.0,2018-04-23,0
4,Ford,C-Max,NaN,2007.0,MPV,84786.0,1.6L,Manual,Petrol,NaN,5.0,5.0,Tyre Alignment,0,2018-05-20,1,10.2600,0.5,2018-05-20,0

Cantidad de datos por cada dataset

In [11]:
df_test.shape

(21826, 20)

In [12]:
df_train.shape

(196429, 20)

### Tipos de datos de dataset train

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196429 entries, 0 to 196428
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   marca                   196429 non-null  object
 1   modelo                  177768 non-null  object
 2   color                   191581 non-null  object
 3   anio_registro           191599 non-null  float64
 4   tipo_vehiculo           196429 non-null  object
 5   millas_recorridas       193664 non-null  float64
 6   tamanio_motor           195482 non-null  object
 7   transmision             196429 non-null  object
 8   tipo_combustible        196429 non-null  object
 9   precio_vehiculo         186867 non-null  float64
 10  num_asientos            196429 non-null  float64
 11  num_puertas             196429 non-null  float64
 12  problema_averia         196429 non-null  object
 13  id_problema_averia      196429 non-null  int64
 14  fecha_averia            196429 non-null  object
 15  complejidad_reparacion  196429 non-null  int64
 16  costo_reparacion        196429 non-null  float64
 17  horas_reparacion        196429 non-null  float64
 18  fecha_reparacion        196429 non-null  object
 19  fraude                  196429 non-null  int64
dtypes: float64(7), int64(3), object(10)
memory usage: 30.0+ MB

### Tipos de datos dataset test

In [14]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21826 entries, 0 to 21825
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   index                   21826 non-null  int64
 1   marca                   21826 non-null  object
 2   modelo                  19719 non-null  object
 3   color                   21281 non-null  object
 4   anio_registro           21298 non-null  float64
 5   tipo_vehiculo           21826 non-null  object
 6   millas_recorridas       21510 non-null  float64
 7   tamanio_motor           21717 non-null  object
 8   transmision             21826 non-null  object
 9   tipo_combustible        21826 non-null  object
 10  precio_vehiculo         20805 non-null  float64
 11  num_asientos            21826 non-null  float64
 12  num_puertas             21826 non-null  float64
 13  problema_averia         21826 non-null  object
 14  id_problema_averia      21826 non-null  int64
 15  fecha_averia            21826 non-null  object
 16  complejidad_reparacion  21826 non-null  int64
 17  costo_reparacion        21826 non-null  float64
 18  horas_reparacion        21826 non-null  float64
 19  fecha_reparacion        21826 non-null  object
dtypes: float64(7), int64(3), object(10)
memory usage: 3.3+ MB

Conclusión: se observan valores faltantes y datos aberrantes en ambos datasets.