In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from constants import tratados_dir

In [2]:
df_test = pd.read_csv(f'{tratados_dir}/vehiculos_test.csv')
df_train = pd.read_csv(f'{tratados_dir}/vehiculos_train.csv')

Definir el umbral mínimo de frecuencia para considerar una marca como representativa utlizando la diferencia entre la media y la desviaicon estandar.

In [3]:
umbral = 6000

In [4]:


 # por ejemplo, marcas con menos de 50 apariciones se agrupan en "OTROS"

# Calcular la frecuencia de cada marca
frecuencias = df_train['marca'].value_counts()

In [5]:
frecuencias

marca
Ford          17854
Audi          14599
Vauxhall      14174
Volkswagen    11737
BMW            9905
              ...
GMC               2
Perodua           2
Zenos             1
Jensen            1
Grinnall          1
Name: count, Length: 64, dtype: int64

In [6]:
# Create new column 'marca2' where rare brands are renamed to 'OTROS'
df_train['marca2'] = df_train['marca'].apply(lambda x: x if frecuencias[x] >= umbral else 'OTROS')

df_test['marca2'] = df_test['marca'].apply(lambda x: x if frecuencias[x] >= umbral else 'OTROS')

In [7]:
# Check the new distribution of brands
print("Train: ", df_train['marca2'].value_counts())
print("Test: ", df_test['marca2'].value_counts())

Train:  marca2
OTROS         76815
Ford          17854
Audi          14599
Vauxhall      14174
Volkswagen    11737
BMW            9905
Nissan         8969
Peugeot        7829
Citroen        6662
Toyota         6612
Name: count, dtype: int64
Test:  marca2
OTROS         8407
Ford          2083
Vauxhall      1631
Audi          1594
Volkswagen    1348
BMW           1059
Nissan         953
Citroen        807
Peugeot        806
Toyota         771
Name: count, dtype: int64

In [8]:
# Aplicamos one-hot encoding a la columna 'marca2'
df_train_encoded = pd.get_dummies(df_train, columns=['marca2'])

# Si deseas que los valores codificados sean 0 y 1 (en número, no booleanos):
columnas_marca = [col for col in df_train_encoded.columns if col.startswith('marca2_')]

# Convertimos a numérico (0 y 1 en lugar de True/False)
for col in columnas_marca:
    df_train_encoded[col] = df_train_encoded[col].replace({True: 1, False: 0})
    df_train_encoded[col] = pd.to_numeric(df_train_encoded[col])

C:\Users\smithinator\AppData\Local\Temp\ipykernel_15688\630973813.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train_encoded[col] = df_train_encoded[col].replace({True: 1, False: 0})

In [9]:
df_train_encoded.head()

,Unnamed: 0,marca,modelo,color,anio_registro,tipo_vehiculo,millas_recorridas,tamanio_motor,transmision,tipo_combustible,...,marca2_Audi,marca2_BMW,marca2_Citroen,marca2_Ford,marca2_Nissan,marca2_OTROS,marca2_Peugeot,marca2_Toyota,marca2_Vauxhall,marca2_Volkswagen
0,0,Jeep,Renegade,Black,2018.0,SUV,17.0,1.4L,Manual,Petrol,...,0,0,0,0,0,1,0,0,0,0
1,1,Vauxhall,Insignia,Grey,2011.0,Hatchback,93000.0,1.2L,Manual,Petrol,...,0,0,0,0,0,0,0,0,1,0
2,2,Mercedes-Benz,GLC Class,White,2019.0,SUV,6879.0,2.0L,Automatic,Diesel,...,0,0,0,0,0,1,0,0,0,0
3,3,Renault,Clio,White,2014.0,Hatchback,20669.0,1.2L,Manual,Petrol,...,0,0,0,0,0,1,0,0,0,0
4,4,Ford,C-Max,Blue,2007.0,MPV,84786.0,1.6L,Manual,Petrol,...,0,0,0,1,0,0,0,0,0,0

In [10]:
df_train_encoded.columns

Index(['Unnamed: 0', 'marca', 'modelo', 'color', 'anio_registro',
       'tipo_vehiculo', 'millas_recorridas', 'tamanio_motor', 'transmision',
       'tipo_combustible', 'precio_vehiculo', 'num_asientos', 'num_puertas',
       'problema_averia', 'id_problema_averia', 'fecha_averia',
       'complejidad_reparacion', 'costo_reparacion', 'horas_reparacion',
       'fecha_reparacion', 'fraude', 'marca2_Audi', 'marca2_BMW',
       'marca2_Citroen', 'marca2_Ford', 'marca2_Nissan', 'marca2_OTROS',
       'marca2_Peugeot', 'marca2_Toyota', 'marca2_Vauxhall',
       'marca2_Volkswagen'],
      dtype='object')

In [11]:
# Aplicamos one-hot encoding a la columna 'marca2'
df_test_encoded = pd.get_dummies(df_test, columns=['marca2'])

# Si deseas que los valores codificados sean 0 y 1 (en número, no booleanos):
columnas_marca = [col for col in df_test_encoded.columns if col.startswith('marca2_')]

# Convertimos a numérico (0 y 1 en lugar de True/False)
for col in columnas_marca:
    df_test_encoded[col] = df_test_encoded[col].replace({True: 1, False: 0})
    df_test_encoded[col] = pd.to_numeric(df_test_encoded[col])

C:\Users\smithinator\AppData\Local\Temp\ipykernel_15688\1942201158.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test_encoded[col] = df_test_encoded[col].replace({True: 1, False: 0})

In [12]:
df_test_encoded.head()

,Unnamed: 0,index,marca,modelo,color,anio_registro,tipo_vehiculo,millas_recorridas,tamanio_motor,transmision,...,marca2_Audi,marca2_BMW,marca2_Citroen,marca2_Ford,marca2_Nissan,marca2_OTROS,marca2_Peugeot,marca2_Toyota,marca2_Vauxhall,marca2_Volkswagen
0,0,0,Volkswagen,2.0L,Blue,2015.0,Saloon,37723.0,2.0L,Automatic,...,0,0,0,0,0,0,0,0,0,1
1,1,1,Jaguar,2.2L,White,2014.0,Saloon,78000.0,2.2L,Automatic,...,0,0,0,0,0,1,0,0,0,0
2,2,2,Volkswagen,1.4L,Orange,2010.0,Hatchback,44936.0,1.4L,Automatic,...,0,0,0,0,0,0,0,0,0,1
3,3,3,Audi,3.0L,Black,2014.0,Coupe,29000.0,3.0L,Automatic,...,1,0,0,0,0,0,0,0,0,0
4,4,4,Toyota,1.33L,Black,2016.0,Hatchback,18037.0,1.33L,Manual,...,0,0,0,0,0,0,0,1,0,0

In [13]:
from constants import predictor_vars

In [14]:
df_train_encoded[predictor_vars]
df_test_encoded[predictor_vars]

,anio_registro,millas_recorridas,precio_vehiculo,num_asientos,num_puertas,complejidad_reparacion,costo_reparacion,horas_reparacion,marca2_Audi,marca2_BMW,marca2_Citroen,marca2_Ford,marca2_Nissan,marca2_OTROS,marca2_Peugeot,marca2_Toyota,marca2_Vauxhall,marca2_Volkswagen
0,2015.0,37723.0,12690.0,5.0,4.0,1,23.807,1.0,0,0,0,0,0,0,0,0,0,1
1,2014.0,78000.0,13490.0,5.0,4.0,3,73.490,3.0,0,0,0,0,0,1,0,0,0,0
2,2010.0,44936.0,8995.0,5.0,5.0,1,160.000,2.0,0,0,0,0,0,0,0,0,0,1
3,2014.0,29000.0,22990.0,4.0,3.0,1,42.990,1.0,1,0,0,0,0,0,0,0,0,0
4,2016.0,18037.0,9293.0,5.0,5.0,1,28.586,0.5,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19454,2014.0,43000.0,9795.0,7.0,5.0,1,25.877,1.0,0,0,0,0,0,0,1,0,0,0
19455,2013.0,39351.0,7990.0,5.0,5.0,1,43.995,2.0,0,0,0,0,0,0,0,1,0,0
19456,2009.0,100000.0,1800.0,5.0,5.0,1,40.900,2.0,0,0,0,0,0,1,0,0,0,0
19457,2012.0,69000.0,3995.0,5.0,5.0,1,119.900,2.0,0,0,0,0,0,0,0,0,1,0
19458,2017.0,8911.0,19250.0,4.0,3.0,1,49.625,2.0,0,0,0,0,0,0,0,0,0,1

In [15]:
import os
from constants import converted_dir

In [16]:
os.makedirs(converted_dir, exist_ok=True)

In [17]:
df_train_encoded.to_csv(f"{converted_dir}/vehiculos_train.csv")
df_test_encoded.to_csv(f"{converted_dir}/vehiculos_test.csv")